import {
  spfOne,
  spfTwo,
  spfThree,
  spfFour,
  bestSellerOne,
  bestSellerTwo,
  bestSellerThree,
  bestSellerFour,
  newArrOne,
  newArrTwo,
  newArrThree,
  newArrFour,
  imprimante1,
  imprimante2,
  imprimante4,
  imprimante5,
  imprimante6,
  imprimante7,
  imprimante8,
  imprimante9,
  encre1,
  encre2,
  encre3,
  encre4,
  ruban1,
  ruban2,
  ruban3,
  ruban4,
  bac1,
  bac2,
  bac3,
  bac4,
  pdf1,
  IMPRIMANTE_PANTUM_CP2200DW,
  IMPRIMANTE_PANTUM_BM5100FDW,
  IMPRIMANTE_PANTUM_M6609N,
  IMPRIMANTE_PANTUM_P3300DN,
  IMPRIMANTE_PANTUM_P3300DW,
  IMPRIMANTE_PANTUM_P2509W,
  IMPRIMANTE_PANTUM_BP5100DN,
  IMPRIMANTE_PANTUM_M6559N,
  IMPRIMANTE_PANTUM_P2509,
  hp1,
  hp2,
  hp3,
  ricoh1,
  ricoh2,
  ricoh3,
  ricoh4,
  ricoh5,
  espson1,
  espson2,
} from "../assets/images/index";

import "./style.css";

// =================== NavBarList Start here ====================
export const navBarList = [
  {
    _id: 1001,
    title: "Home",
    link: "/",
  },
  {
    _id: 1002,
    title: "Shop",
    link: "/shop",
  },
  {
    _id: 1003,
    title: "About",
    link: "/about",
  },
  {
    _id: 1004,
    title: "Contact",
    link: "contact",
  },
  {
    _id: 1005,
    title: "Journal",
    link: "/journal",
  },
];
// =================== NavBarList End here ======================
// =================== Special Offer data Start here ============
export const SplOfferData = [
  {
    _id: "201",
    img: imprimante1,
    productName: "Octane Signature Analog",
    price: "35.00",
    color: "Blank and White",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Octane Analogue",
  },
  {
    _id: "202",
    img: imprimante2,
    productName: "Octane Blue Dial Quartz Multifunction",
    price: "180.00",
    color: "Gray",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Octane Analogue",
  },
  {
    _id: "203",
    img: imprimante4,
    productName: "Octane Aerobatics Black Dial",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Octane Analogue",
  },
  {
    _id: "204",
    img: imprimante5,
    productName: "Octane Quartz Chronograph White Dial",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Octane Analogue",
  },
  {
    _id: "205",
    img: imprimante6,
    productName: "Octane Hyper Lume Black Dial Quartz",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Octane Analogue",
  },
  {
    _id: "206",
    img: imprimante7,
    productName: "Octane Black Dial Chrono Metal Strap",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Octane Analogue",
  },
  {
    _id: "207",
    img: imprimante8,
    productName: "Octane White Dial Chrono Stainless",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Octane Analogue",
  },
  {
    _id: "208",
    img: imprimante9,
    productName: "Octane Classic Sporty Green Dial",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Octane Analogue",
  },
  {
    _id: "209",
    img: encre1,
    productName: "Unisex Black & Red Dial & Straps Iron Man Print",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Unisex Classic Smart",
  },
  {
    _id: "210",
    img: encre2,
    productName: "Classic with 1.91 Super HD Display BT Calling Smartwatch",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Unisex Classic Smart",
  },
  {
    _id: "211",
    img: encre3,
    productName: "All Nighters Women Blue Analogue watch ",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Unisex Classic Smart",
  },
  {
    _id: "212",
    img: encre4,
    productName: "Men Brown & Grey Digital Watch",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Unisex Classic Smart",
  },
  {
    _id: "213",
    img: ruban1,
    productName: "Omega Constellation Co-Axial Master Chronometer Black Dial",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Constellation Co-Axial",
  },
  {
    _id: "214",
    img: ruban2,
    productName: "Omega Constellation Double Eagle Co-AxiaI Stainless Steel",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Constellation Co-Axial",
  },
  {
    _id: "215",
    img: ruban3,
    productName: "Omega Constellation Globemaster Omega Co-AxiaI Master",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Constellation Co-Axial",
  },
  {
    _id: "216",
    img: ruban4,
    productName: "Omega Constellation Co-AxiaI 27mm Ladies Watch",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: " Omega Constellation Co-Axial",
  },
  {
    _id: "217",
    img: bac1,
    productName: "Men Black Dial Chronograph Watch JR1354",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Garrett Hr Smartwatch",
  },
  {
    _id: "219",
    img: bac2,
    productName: "Men Black Analogue Watch",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Garrett Hr Smartwatch",
  },
  {
    _id: "220",
    img: bac3,
    productName: "NATE Men Black Analogue Watch JR1353",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Garrett Hr Smartwatch",
  },
  {
    _id: "221",
    img: bac4,
    productName: "Men Black Analogue Watch FS5665",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Garrett Hr Smartwatch",
  },
];
// =================== Special Offer data End here ==============

// =================== PaginationItems Start here ===============

export const paginationItems = [
  {
    _id: "201",
    img: IMPRIMANTE_PANTUM_CP2200DW,
    productName: "Octane Upgrade Analogue",
    price: "35.00",
    color: "Blanc",
    badge: true,
    brand: "Titan",
    des: "Discover the perfect blend of elegance and precision with our exquisite timepieces. Crafted from premium materials and designed for ultimate comfort, each watch ensures reliable performance and versatile style. Embrace sophistication and functionality—experience the art of fine horology.",
    cat: "Octane Analogue",
    // pdf: pdf1,
    // ficheTech: [
    //   { label: "Technology ", value: "Electronic laser watch " },
    //   { label: "fast speed ", value: "22 ppm (A4)/23 ppm (Letter)" },

    //   { label: "First print out time ", value: "Less than 7.8s       " },
    //   { label: "Maximum Monthly Duty Cycle", value: "15,000 pages " },
    //   {
    //     label: "Recommended monthly volume Resolution(dpi) ",
    //     value: "700 pages ",
    //   },
    //   { label: "Printer language Duplex Mode ", value: "Max. 1,200×1,200 " },
    //   { label: "Printer  ", value: "Max. 1,2   " },
    //   { label: "galass  ", value: "Max. 1,2   " },
    // ],
  },
  {
    _id: "202",
    img: IMPRIMANTE_PANTUM_BM5100FDW,
    productName: "Octane Aerobatics Analogue ",
    price: "450",
    color: "Blanc",
    badge: true,
    brand: "Pantum",
    des: "Discover the perfect blend of elegance and precision with our exquisite timepieces. Crafted from premium materials and designed for ultimate comfort, each watch ensures reliable performance and versatile style. Embrace sophistication and functionality—experience the art of fine horology.",
    cat: "Octane Analogue",
    // pdf: pdf1,
    // ficheTech: [
    //   { label: "Vitesse d'impression ", value: "40ppm(A4)/42ppm(lettre) " },
    //   { label: "Temps de sortie de la première page ", value: "≤6.9 s" },

    //   {
    //     label: "Nombre de pages mensuel recommandé",
    //     value: "750 à 4,000 Pages",
    //   },
    //   { label: "Résolution d'impression", value: "Max.1,200x1,200 dpi" },
    //   {
    //     label: "Langage d'impression ",
    //     value: "PCL5e, PCL6, PS        ",
    //   },
    //   { label: "Vitesse du processeur", value: "1.2 GHz" },
    //   { label: "Mémoire", value: "512 MB" },
    //   {
    //     label: "Panneau de commande ",
    //     value: "LCD 2 lignes ||  Écran tactile 3,5 pouces      ",
    //   },
    //   { label: "Impression recto-verso automatique      ", value: "Oui" },
    //   {
    //     label: "Autres fonctions d'impression      ",
    //     value:
    //       "Impression brochure, impression sécurisée, impression disque USB Compatible AirPrint, Mopria, APP mobile (APP iOS/App Android)",
    //   },
    //   { label: "Vitese de copie ", value: "40ppm(A4)/42ppm(lettre)" },
    //   {
    //     label: "Temps de sortie de la première page",
    //     value: "Plateau : moins de 10 s ADF : moins de 11 s",
    //   },
    // ],
  },

  {
    _id: "203",
    img: IMPRIMANTE_PANTUM_BP5100DN,
    productName: "Octane OTS- 3 Wells Analog",
    price: "450",
    color: "Blanc",
    badge: true,
    brand: "Pantum",
    des: "Discover the perfect blend of elegance and precision with our exquisite timepieces. Crafted from premium materials and designed for ultimate comfort, each watch ensures reliable performance and versatile style. Embrace sophistication and functionality—experience the art of fine horology.",
    cat: "Octane Analogue",
    // pdf: pdf1,
    // ficheTech: [
    //   { label: "Vitesse d'impression ", value: "40ppm(A4)/42ppm(lettre) " },
    //   { label: "Temps de sortie de la première page ", value: "≤6.9 s" },

    //   {
    //     label: "Nombre de pages mensuel recommandé",
    //     value: "750 à 4,000 Pages",
    //   },
    //   { label: "Résolution d'impression", value: "Max.1,200x1,200 dpi" },
    //   {
    //     label: "Langage d'impression ",
    //     value: "PCL5e, PCL6, PS        ",
    //   },
    //   { label: "Vitesse du processeur", value: "1.2 GHz" },
    //   { label: "Mémoire", value: "512 MB" },
    //   {
    //     label: "Panneau de commande ",
    //     value: "LCD 2 lignes ||  Écran tactile 3,5 pouces      ",
    //   },
    //   { label: "Impression recto-verso automatique      ", value: "Oui" },
    //   {
    //     label: "Autres fonctions d'impression      ",
    //     value:
    //       "Impression brochure, impression sécurisée, impression disque USB Compatible AirPrint, Mopria, APP mobile (APP iOS/App Android)",
    //   },
    //   { label: "Vitese de copie ", value: "40ppm(A4)/42ppm(lettre)" },
    //   {
    //     label: "Temps de sortie de la première page",
    //     value: "Plateau : moins de 10 s ADF : moins de 11 s",
    //   },
    // ],
  },
  {
    _id: "2005",
    img: IMPRIMANTE_PANTUM_M6609N,
    productName: "Octane Signature Analog ",
    price: "450",
    color: "Blanc",
    badge: true,
    brand: "Pantum",
    des: "Discover the perfect blend of elegance and precision with our exquisite timepieces. Crafted from premium materials and designed for ultimate comfort, each watch ensures reliable performance and versatile style. Embrace sophistication and functionality—experience the art of fine horology.",
    cat: "Octane Analogue",
    // pdf: pdf1,
    // ficheTech: [
    //   { label: "gtin	", value: "M6559N      " },
    //   { label: "Marque	", value: "PANTUM      " },
    //   { label: "fonctions	", value: "Monofonction      " },
    //   { label: "Technologie d impression		", value: "Laser      " },
    //   { label: "Impression	", value: "Noir & Blanc      " },
    //   { label: "Vitesse du Processeur		", value: "600MHz      " },
    //   {
    //     label: "Capacité papier		",
    //     value: "Capacité standard: 1 600 pages      ",
    //   },
    //   { label: "Gestion d entrée Papier Standard		", value: "150 pages      " },
    //   { label: "Premiére Page Imprimée		", value: "Moins de 7.8s      " },
    //   { label: "Cycle d utilisation Mensuel		", value: "15 000 pages      " },
    //   {
    //     label: "Résolution d impression		",
    //     value: "Max. 1 200 × 1 200 ppp      ",
    //   },
    //   {
    //     label: "Résolution d'impression Noir		",
    //     value: "Max. 1 200 × 1 200 ppp      ",
    //   },
    //   { label: "formats		", value: "A4      " },
    //   { label: "Sortie papier		", value: "100 pages      " },
    //   {
    //     label: "Vitesse de Copie Noir Blanc		",
    //     value: "22 ppm (A4) / 23 ppm (Lettre)      ",
    //   },
    //   { label: "Poids		", value: "4,75 kg      " },
    // ],
  },

  {
    _id: "20005",
    img: IMPRIMANTE_PANTUM_M6559N,
    productName: "Octane Signature Analog 2 ",
    price: "450",
    color: "Blanc",
    badge: true,
    brand: "Pantum",
    des: "Discover the perfect blend of elegance and precision with our exquisite timepieces. Crafted from premium materials and designed for ultimate comfort, each watch ensures reliable performance and versatile style. Embrace sophistication and functionality—experience the art of fine horology.",
    cat: "Octane Analogue",
    // pdf: pdf1,
    // ficheTech: [
    //   { label: "gtin	", value: "M6559N      " },
    //   { label: "Marque	", value: "PANTUM      " },
    //   { label: "fonctions	", value: "Monofonction      " },
    //   { label: "Technologie d impression		", value: "Laser      " },
    //   { label: "Impression	", value: "Noir & Blanc      " },
    //   { label: "Vitesse du Processeur		", value: "600MHz      " },
    //   {
    //     label: "Capacité papier		",
    //     value: "Capacité standard: 1 600 pages      ",
    //   },
    //   { label: "Gestion d entrée Papier Standard		", value: "150 pages      " },
    //   { label: "Premiére Page Imprimée		", value: "Moins de 7.8s      " },
    //   { label: "Cycle d utilisation Mensuel		", value: "15 000 pages      " },
    //   {
    //     label: "Résolution d impression		",
    //     value: "Max. 1 200 × 1 200 ppp      ",
    //   },
    //   {
    //     label: "Résolution d'impression Noir		",
    //     value: "Max. 1 200 × 1 200 ppp      ",
    //   },
    //   { label: "formats		", value: "A4      " },
    //   { label: "Sortie papier		", value: "100 pages      " },
    //   {
    //     label: "Vitesse de Copie Noir Blanc		",
    //     value: "22 ppm (A4) / 23 ppm (Lettre)      ",
    //   },
    //   { label: "Poids		", value: "4,75 kg      " },
    // ],
  },

  {
    _id: "206",
    img: IMPRIMANTE_PANTUM_P3300DN,
    productName: "Gents Octane Analog",
    price: "450",
    color: "Blanc",
    badge: true,
    brand: "Pantum",
    des: "Discover the perfect blend of elegance and precision with our exquisite timepieces. Crafted from premium materials and designed for ultimate comfort, each watch ensures reliable performance and versatile style. Embrace sophistication and functionality—experience the art of fine horology.",
    cat: "Octane Analogue",
    // pdf: pdf1,
    // ficheTech: [
    //   { label: "gtin	", value: "P3300DN      " },
    //   { label: "fonctions	", value: "Monofonction      " },
    //   { label: "Mémoire	", value: "256MO      " },
    //   { label: "Technologie d impression		", value: "laser      " },
    //   { label: "Impression		", value: "Noir & Blanc      " },
    //   { label: "Connectivite		", value: "Réseau      " },
    //   { label: "Vitesse du Processeur		", value: "350 MHz      " },
    //   { label: "Type ecran		", value: "LCD 2 lignes      " },
    //   {
    //     label: "Consommation d énergie		",
    //     value:
    //       "Impression : 525 W en moyenne Veille : 50 W en veille : moins de 2 W      ",
    //   },
    //   {
    //     label: "Gestion d entrée Papier Standard		",
    //     value: "Papier Bac d'alimentation: 250pages      ",
    //   },
    //   { label: "Premiére Page Imprimée		", value: "Moins de 8,2 secondes      " },
    //   {
    //     label: "Vitesse d impression Noir		",
    //     value: "33 ppm (A4) / 35 ppm (Lettre)      ",
    //   },
    //   { label: "Cycle d utilisation Mensuel		", value: "60000pages      " },
    //   {
    //     label: "Résolution d impression		",
    //     value: "1 200 x 1 200 dpi (maximum)      ",
    //   },
    //   { label: "formats	", value: "A4      " },
    //   {
    //     label: "Connecteurs		",
    //     value: "USB2.0 haut débit / Ethernet：IEEE 802.3 10/100Base-Tx      ",
    //   },
    //   { label: "Fonctionnalités		", value: "Impression      " },
    //   {
    //     label: "Volume de Pages Mensuel Recommandé		",
    //     value: "750 à 3 500 pages      ",
    //   },
    //   { label: "Dimensions		", value: "354 x 334 x 232mm      " },
    //   { label: "Garantie	", value: "1ANS      " },
    // ],
  },

  {
    _id: "207",
    img: IMPRIMANTE_PANTUM_P3300DW,
    productName: "Octane Phoenix Analog",
    price: "450",
    color: "Blanc",
    badge: true,
    brand: "Pantum",
    des: "Discover the perfect blend of elegance and precision with our exquisite timepieces. Crafted from premium materials and designed for ultimate comfort, each watch ensures reliable performance and versatile style. Embrace sophistication and functionality—experience the art of fine horology.",
    cat: "Octane Analogue",
    // pdf: pdf1,
    // ficheTech: [
    //   { label: "gtin		", value: "P3300DW      " },
    //   { label: "fonctions	", value: "Monofonction      " },
    //   { label: "Mémoire	", value: "256 Mo      " },
    //   { label: "Technologie d impression		", value: "Laser      " },
    //   { label: "Connectivite	", value: "WIFI      " },
    //   { label: "Vitesse du Processeur		", value: "350 MHz      " },
    //   { label: "Type ecran		", value: "LCD 2 lignes      " },
    //   {
    //     label: "Consommation d énergie		",
    //     value:
    //       "Impression : 525 W en moyenne Veille : 50 W en veille : moins de 2 W      ",
    //   },
    //   {
    //     label: "Gestion d entrée Papier Standard		",
    //     value: "Papier Bac d'alimentation: 250pages      ",
    //   },
    //   { label: "Premiére Page Imprimée		", value: "Moins de 8,2 secondes      " },
    //   {
    //     label: "Vitesse d impression Noir		",
    //     value: "33 ppm (A4) / 35 ppm (Lettre)      ",
    //   },
    //   { label: "Cycle d utilisation Mensuel		", value: "60000pages      " },
    //   { label: "Résolution d impression		", value: "Max.1200x1200 dpi      " },
    //   {
    //     label: "Volume de Pages Mensuel Recommandé		",
    //     value: "750 à 3 500 pages      ",
    //   },
    //   {
    //     label: "Interface Réseau	",
    //     value:
    //       "Ethernet USB 2.0 haut débit : Wi-Fi IEEE 802.3 10/100Base-Tx : IEEE 802.11b/g/n      ",
    //   },
    //   {
    //     label: "Contenu de L'emballage		",
    //     value:
    //       "Imprimante - Cordon d’alimentation - Câble d’interface USB - Plateau de sortie - CD-ROM - Guide de configuration rapide      ",
    //   },
    //   { label: "Garantie	", value: "1 ANS      " },
    // ],
  },

  {
    _id: "208",
    img: IMPRIMANTE_PANTUM_P2509W,
    productName: "Octane Phoenix Analog 2",
    price: "450",
    color: "Blanc",
    badge: true,
    brand: "Pantum",
    des: "Discover the perfect blend of elegance and precision with our exquisite timepieces. Crafted from premium materials and designed for ultimate comfort, each watch ensures reliable performance and versatile style. Embrace sophistication and functionality—experience the art of fine horology.",
    cat: "Octane Analogue",
    // pdf: pdf1,
    // ficheTech: [
    //   { label: "gtin	", value: "P2509W      " },
    //   { label: "fonctions	", value: "Monofonction      " },
    //   { label: "Technologie d impression		", value: "Laser      " },
    //   { label: "Ecran Tactile		", value: "Non      " },
    //   { label: "Connectivite	", value: "WiFi      " },
    //   { label: "Vitesse du Processeur		", value: "600MHz      " },
    //   {
    //     label: "Capacité papier		",
    //     value: "Capacité standard: 1 600 pages      ",
    //   },
    //   { label: "Premiére Page Imprimée		", value: "Moins de 7.8s      " },
    //   { label: "Cycle d utilisation Mensuel		", value: "15 000 pages      " },
    //   {
    //     label: "Résolution d impression		",
    //     value: "Max. 1 200 × 1 200 ppp      ",
    //   },
    //   { label: "formats	", value: "A4      " },
    //   { label: "Connecteurs		", value: "USB 2.0, Wi-Fi      " },
    //   {
    //     label: "Vitesse de Copie Noir Blanc		",
    //     value: "22 ppm (A4) / 23 ppm (Lettre)      ",
    //   },
    //   {
    //     label: "Contenu de L'emballage		",
    //     value:
    //       "Imprimante - Cordon d’alimentation - Câble d’interface USB - Plateau de sortie - CD-ROM - Guide de configuration rapide      ",
    //   },
    //   { label: "Dimensions		", value: "337 x 220 x 178 mm      " },
    // ],
  },
  {
    _id: "233",
    img: IMPRIMANTE_PANTUM_P2509,
    productName: "Octane upgrade Analog 2",
    price: "450",
    color: "Blanc",
    badge: true,
    brand: "Pantum",
    des: " Discover the perfect blend of elegance and precision with our exquisite timepieces. Crafted from premium materials and designed for ultimate comfort, each watch ensures reliable performance and versatile style. Embrace sophistication and functionality—experience the art of fine horology.",
    cat: "Octane Analogue",
    pdf: pdf1,
    ficheTech: [],
  },
  {
    _id: "220",
    img: bac3,
    productName: "Fossil Townsman Auto Smoke",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Garrett Hr Smartwatch",
  },
  {
    _id: "221",
    img: bac4,
    productName: "Fastrack Magnus FX3 Premium Metal",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Garrett Hr Smartwatch",
  },
  {
    _id: "215",
    img: ruban3,
    productName: "Omega Gold Constellation Coaxial Day Date 38mm Watch",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Constellation Co-Axial",
  },
  {
    _id: "216",
    img: ruban4,
    productName: "OMEGA DOUBLE EAGLE CO-aXIAL CHRONOGRAPH ome...",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Constellation Co-Axial",
  },
  {
    _id: "209",
    img: encre1,
    productName: " Fastrack Unisex Classic Smart",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Unisex Classic Smart",
  },
  {
    _id: "210",
    img: encre2,
    productName: "Fastrack Reflex Unisex Smart Band ",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Unisex Classic Smart",
  },

  {
    _id: "211",
    img: encre3,
    productName: "Fastrack Unisex Reflex Vox",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Unisex Classic Smart",
  },
  {
    _id: "212",
    img: encre4,
    productName: "Fastrack Reflex Digital Dial Unisex",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Unisex Classic Smart",
  },
  {
    _id: "213",
    img: ruban1,
    productName: "Reloj Omega Constellation Co-axial Master Chronometer 3...",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Constellation Co-Axial",
  },
  {
    _id: "214",
    img: ruban2,
    productName: "Omega Constellation Co-axial Chronometer Black 38mm F...",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Constellation Co-Axial",
  },

  {
    _id: "217",
    img: bac1,
    productName: "Fossil Men Navy Blue Analogue Watch BQ2401",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Garrett Hr Smartwatch",
  },
  {
    _id: "219",
    img: bac2,
    productName: "Fossil Men Leather Straps AnalogueChronograph Watch- FS5403 SOR",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
    cat: "Garrett Hr Smartwatch",
  },

 

  {
    _id: "hp1",
    img: hp1,
    productName:
      "Titan gold 2.0",
    price: "450",
    color: "Blanc",
    badge: true,
    brand: "Titan",
    des: "Desc : Discover the perfect blend of elegance and precision with our exquisite timepieces. Crafted from premium materials and designed for ultimate comfort, each watch ensures reliable performance and versatile style. Embrace sophistication and functionality—experience the art of fine horology.",
    cat: "Octane Analogue",
    // pdf: pdf1,
    // ficheTech: [
    //   { label: "DISPONIBILITÉ", value: "En stock" },
    //   { label: "gtin", value: "3YW70A" },
    //   { label: "Marque", value: "HP" },
    //   { label: "Destockage", value: "Non" },
    //   { label: "Ecran", value: "LCD" },
    //   {
    //     label: "Taille de L écran cm",
    //     value: "Affichage LCD 7 segments + icône 5,08 cm (2 pouces)",
    //   },
    //   { label: "Ecran Tactile", value: "Non" },
    //   { label: "Technologie d impression", value: "Jet d'encre" },
    //   { label: "fonctions", value: "Multifonction" },
    //   { label: "Fonctionnalités", value: "Impression, Copie, Numérisation" },
    //   { label: "Impression", value: "Couleur" },
    //   { label: "formats", value: "A4" },
    //   { label: "Chargement de Documents", value: "Oui" },
    //   { label: "Vitesse d impression Noir", value: "Jusqu'à 22 ppm" },
    //   { label: "Vitesse d impression Couleur", value: "Jusqu'à 16 ppm" },
    //   { label: "FAX", value: "Non" },
    //   { label: "Mémoire", value: "256 Mo" },
    //   {
    //     label: "Qualité d impression Noir",
    //     value: "Jusqu'à 1 200 x 1 200 ppp",
    //   },
    //   {
    //     label: "Qualité d impression Couleur",
    //     value: "Jusqu'à 4 800 x 1 200 ppp",
    //   },
    //   { label: "Résolution d impression Couleur", value: "1200x1200dpi" },
    //   { label: "Recto/Verso", value: "Manuel" },
    //   { label: "Type de Scanner", value: "Scanner à Plat" },
    //   { label: "Connectivite", value: "USB 2.0, WiFi" },
    //   { label: "Capacité papier", value: "100 feuilles" },
    //   { label: "Cycle d utilisation Mensuel", value: "Jusqu'à 1000 pages" },
    //   {
    //     label: "Consommation électrique",
    //     value:
    //       "0,12 Watts (Arrêt manuel), 3,12 Watts (Prêt), 0,75 Watt (Veille) 5",
    //   },
    //   { label: "Grammage", value: "75 g/m²" },
    //   {
    //     label: "Contenu de L'emballage",
    //     value:
    //       "Imprimante HP Smart Tank 516, Bouteilles d'encre: 3 x HP GT53XL (noir), 3 x HP GT52 (cyan, magenta et jaune), Notice de précaution pour l'encre; Fiche pour le ré-emballage et réglementaire RoH-EAC; Cordon d'alimentation, Guide d'installation; Notice PT",
    //   },
    //   { label: "Poids", value: "5,14 kg" },
    //   { label: "Dimensions", value: "447 x 373 x 158 mm" },
    //   { label: "Couleur", value: "Noir et Bleu" },
    //   { label: "Garantie", value: "1 an" },
    // ],
  },

  {
    _id: "hp2",
    img: hp2,
    productName: "Titan Thunderstorm",
    price: "450",
    color: "Blanc",
    badge: true,
    brand: "Titan",
    des: "Desc : Discover the perfect blend of elegance and precision with our exquisite timepieces. Crafted from premium materials and designed for ultimate comfort, each watch ensures reliable performance and versatile style. Embrace sophistication and functionality—experience the art of fine horology.",
    cat: "Octane Analogue",
    pdf: pdf1,
    ficheTech: [],
  },

  {
    _id: "hp3",
    img: hp3,
    productName: "Octane Titan Luxury",
    price: "450",
    color: "Blanc",
    badge: true,
    brand: "Titan",
    des: "Discover the perfect blend of elegance and precision with our exquisite timepieces. Crafted from premium materials and designed for ultimate comfort, each watch ensures reliable performance and versatile style. Embrace sophistication and functionality—experience the art of fine horology.",
    cat: "Octane Analogue",
    // pdf: pdf1,
    // ficheTech: [
    //   { label: "DISPONIBILITÉ", value: "En stock" },
    //   { label: "gtin", value: "Z4B04A" },
    //   { label: "Marque", value: "HP" },
    //   { label: "Destockage", value: "Non" },
    //   { label: "Technologie d impression", value: "Multifonction Jet d'encre" },
    //   { label: "fonctions", value: "Multifonction" },
    //   { label: "Impression", value: "Couleur" },
    //   { label: "Mémoire", value: "Non" },
    //   { label: "FAX", value: "Non" },
    //   { label: "Fonctionnalités", value: "Impression, Copie, Numérisation" },
    //   { label: "Chargement de Documents", value: "Oui" },
    //   { label: "Connecteurs", value: "1 port USB 2.0 haut débit" },
    //   { label: "Vitesse du Processeur", value: "360 MHz" },
    //   {
    //     label: "Impression sans bordure",
    //     value: "Oui, jusqu’à 210 x 297 mm (A4)",
    //   },
    //   { label: "Vitesse d impression Noir", value: "Jusqu'à 19 ppm" },
    //   { label: "Vitesse d impression Couleur", value: "Jusqu'à 15 ppm" },
    //   {
    //     label: "Résolution d'impression Noir",
    //     value: "Jusqu'à 1 200 x 1 200 DPI",
    //   },
    //   {
    //     label: "Résolution d impression Couleur",
    //     value: "Jusqu'à 4 800 x 1 200 DPI (couleur)",
    //   },
    //   {
    //     label: "Résolution d impression",
    //     value:
    //       "Jusqu'à 1 200 x 1 200 DPI (noir), Jusqu'à 4 800 x 1 200 DPI (couleur)",
    //   },
    //   { label: "Type de Scanner", value: "Scanner à Plat" },
    //   { label: "Vitesse de numérisation", value: "Jusqu'à 21 secondes" },
    //   { label: "Résolution de Numérisation", value: "Jusqu'à 1200 x 1200 ppp" },
    //   {
    //     label: "Résolution de numérisation optimisée",
    //     value: "Jusqu’à 1200 ppp",
    //   },
    //   { label: "Recto/Verso", value: "Manuel" },
    //   { label: "Connectivite", value: "USB" },
    //   { label: "formats", value: "A4" },
    //   {
    //     label: "Premiére Page Imprimée",
    //     value:
    //       "Noir: (A4, prêt) Vitesse : 14 s - Couleur (A4, prêt) Vitesse : 18 s",
    //   },
    //   {
    //     label: "Alimentation-courant",
    //     value:
    //       "Tension d'entrée : 220 à 240 V CA (+/- 10 %), 50/60 Hz (+/- 3 Hz)",
    //   },
    //   {
    //     label: "Type de Papier pris en charge",
    //     value:
    //       "Papier ordinaire, papiers photo HP, papier mat pour brochure HP ou papier professionnel HP, papier mat pour présentation HP, papier brillant pour brochure HP ou papier professionnel HP, papiers photo jet d'encre, papiers mats jet d'encre, papiers brillant",
    //   },
    //   {
    //     label: "Consommation électrique",
    //     value:
    //       "10 W maximum, 0,07 W (Arrêt), 2,1 W (Veille), 0,88 W (Veille prolongée)",
    //   },
    //   {
    //     label: "Cycle d utilisation Mensuel",
    //     value: "A4: Jusqu'à 1 000 pages - Lettre: Jusqu'à 1 000 pages",
    //   },
    //   {
    //     label: "Alimentation papier standard",
    //     value:
    //       "Bac d'alimentation de 60 feuilles - Bac de sortie de 25 feuilles",
    //   },
    //   { label: "Ecran Tactile", value: "Non" },
    //   { label: "Type ecran", value: "7 segments et icône LCD" },
    //   {
    //     label: "Volume de Pages Mensuel Recommandé",
    //     value: "400 à 800 (Jusqu'à 1000 pages)",
    //   },
    //   { label: "Interfaces standard", value: "1x port USB 2.0 haut débit" },
    //   { label: "Résolution optique", value: "Jusqu'à 1200 x 1200 ppp" },
    //   { label: "Grammage", value: "75 g/m²" },
    //   {
    //     label: "Contenu de L'emballage",
    //     value:
    //       "HP Ink Tank 315 , cartouche d'encre noire HP GT51 (90CC), cartouche d'encre cyan HP GT52 (70CC), cartouche d'encre magenta HP GT52 (70CC), cartouche d'encre jaune HP GT52 (70CC)",
    //   },
    //   { label: "Poids", value: "4,67 kg" },
    //   { label: "Couleur", value: "Noir" },
    //   { label: "Dimensions", value: "525 x 310 x 158 mm" },
    //   { label: "Garantie", value: "1 an" },
    // ],
  },

  {
    _id: "ricoh1",
    img: ricoh1,
    productName: "Titan Premium",
    price: "450",
    color: "Blanc",
    badge: true,
    brand: "Titan",
    des: "Discover the perfect blend of elegance and precision with our exquisite timepieces. Crafted from premium materials and designed for ultimate comfort, each watch ensures reliable performance and versatile style. Embrace sophistication and functionality—experience the art of fine horology.",
    cat: "Octane Analogue",
    // pdf: pdf1,
    // ficheTech: [
    //   { label: "DISPONIBILITÉ", value: "En stock" },
    //   { label: "gtin", value: "Z4B04A" },
    //   { label: "Marque", value: "HP" },
    //   { label: "Destockage", value: "Non" },
    //   { label: "Technologie d impression", value: "Multifonction Jet d'encre" },
    //   { label: "fonctions", value: "Multifonction" },
    //   { label: "Impression", value: "Couleur" },
    //   { label: "Mémoire", value: "Non" },
    //   { label: "FAX", value: "Non" },
    //   { label: "Fonctionnalités", value: "Impression, Copie, Numérisation" },
    //   { label: "Chargement de Documents", value: "Oui" },
    //   { label: "Connecteurs", value: "1 port USB 2.0 haut débit" },
    //   { label: "Vitesse du Processeur", value: "360 MHz" },
    //   {
    //     label: "Impression sans bordure",
    //     value: "Oui, jusqu’à 210 x 297 mm (A4)",
    //   },
    //   { label: "Vitesse d impression Noir", value: "Jusqu'à 19 ppm" },
    //   { label: "Vitesse d impression Couleur", value: "Jusqu'à 15 ppm" },
    //   {
    //     label: "Résolution d'impression Noir",
    //     value: "Jusqu'à 1 200 x 1 200 DPI",
    //   },
    //   {
    //     label: "Résolution d impression Couleur",
    //     value: "Jusqu'à 4 800 x 1 200 DPI (couleur)",
    //   },
    //   {
    //     label: "Résolution d impression",
    //     value:
    //       "Jusqu'à 1 200 x 1 200 DPI (noir), Jusqu'à 4 800 x 1 200 DPI (couleur)",
    //   },
    //   { label: "Type de Scanner", value: "Scanner à Plat" },
    //   { label: "Vitesse de numérisation", value: "Jusqu'à 21 secondes" },
    //   { label: "Résolution de Numérisation", value: "Jusqu'à 1200 x 1200 ppp" },
    //   {
    //     label: "Résolution de numérisation optimisée",
    //     value: "Jusqu’à 1200 ppp",
    //   },
    //   { label: "Recto/Verso", value: "Manuel" },
    //   { label: "Connectivite", value: "USB" },
    //   { label: "formats", value: "A4" },
    //   {
    //     label: "Premiére Page Imprimée",
    //     value:
    //       "Noir: (A4, prêt) Vitesse : 14 s - Couleur (A4, prêt) Vitesse : 18 s",
    //   },
    //   {
    //     label: "Alimentation-courant",
    //     value:
    //       "Tension d'entrée : 220 à 240 V CA (+/- 10 %), 50/60 Hz (+/- 3 Hz)",
    //   },
    //   {
    //     label: "Type de Papier pris en charge",
    //     value:
    //       "Papier ordinaire, papiers photo HP, papier mat pour brochure HP ou papier professionnel HP, papier mat pour présentation HP, papier brillant pour brochure HP ou papier professionnel HP, papiers photo jet d'encre, papiers mats jet d'encre, papiers brillant",
    //   },
    //   {
    //     label: "Consommation électrique",
    //     value:
    //       "10 W maximum, 0,07 W (Arrêt), 2,1 W (Veille), 0,88 W (Veille prolongée)",
    //   },
    //   {
    //     label: "Cycle d utilisation Mensuel",
    //     value: "A4: Jusqu'à 1 000 pages - Lettre: Jusqu'à 1 000 pages",
    //   },
    //   {
    //     label: "Alimentation papier standard",
    //     value:
    //       "Bac d'alimentation de 60 feuilles - Bac de sortie de 25 feuilles",
    //   },
    //   { label: "Ecran Tactile", value: "Non" },
    //   { label: "Type ecran", value: "7 segments et icône LCD" },
    //   {
    //     label: "Volume de Pages Mensuel Recommandé",
    //     value: "400 à 800 (Jusqu'à 1000 pages)",
    //   },
    //   { label: "Interfaces standard", value: "1x port USB 2.0 haut débit" },
    //   { label: "Résolution optique", value: "Jusqu'à 1200 x 1200 ppp" },
    //   { label: "Grammage", value: "75 g/m²" },
    //   {
    //     label: "Contenu de L'emballage",
    //     value:
    //       "HP Ink Tank 315 , cartouche d'encre noire HP GT51 (90CC), cartouche d'encre cyan HP GT52 (70CC), cartouche d'encre magenta HP GT52 (70CC), cartouche d'encre jaune HP GT52 (70CC)",
    //   },
    //   { label: "Poids", value: "4,67 kg" },
    //   { label: "Couleur", value: "Noir" },
    //   { label: "Dimensions", value: "525 x 310 x 158 mm" },
    //   { label: "Garantie", value: "1 an" },
    // ],
  },

  {
    _id: "ricoh2",
    img: ricoh2,
    productName: "Ultra Smart Fastrack",
    price: "450",
    color: "Blanc",
    badge: true,
    brand: "Fastrack",
    des: "Discover the perfect blend of elegance and precision with our exquisite timepieces. Crafted from premium materials and designed for ultimate comfort, each watch ensures reliable performance and versatile style. Embrace sophistication and functionality—experience the art of fine horology.",
    cat: "Unisex Classic Smart",
    // pdf: pdf1,
    // ficheTech: [
    //   { label: "DISPONIBILITÉ", value: "En stock" },
    //   { label: "gtin", value: "Z4B04A" },
    //   { label: "Marque", value: "HP" },
    //   { label: "Destockage", value: "Non" },
    //   { label: "Technologie d impression", value: "Multifonction Jet d'encre" },
    //   { label: "fonctions", value: "Multifonction" },
    //   { label: "Impression", value: "Couleur" },
    //   { label: "Mémoire", value: "Non" },
    //   { label: "FAX", value: "Non" },
    //   { label: "Fonctionnalités", value: "Impression, Copie, Numérisation" },
    //   { label: "Chargement de Documents", value: "Oui" },
    //   { label: "Connecteurs", value: "1 port USB 2.0 haut débit" },
    //   { label: "Vitesse du Processeur", value: "360 MHz" },
    //   {
    //     label: "Impression sans bordure",
    //     value: "Oui, jusqu’à 210 x 297 mm (A4)",
    //   },
    //   { label: "Vitesse d impression Noir", value: "Jusqu'à 19 ppm" },
    //   { label: "Vitesse d impression Couleur", value: "Jusqu'à 15 ppm" },
    //   {
    //     label: "Résolution d'impression Noir",
    //     value: "Jusqu'à 1 200 x 1 200 DPI",
    //   },
    //   {
    //     label: "Résolution d impression Couleur",
    //     value: "Jusqu'à 4 800 x 1 200 DPI (couleur)",
    //   },
    //   {
    //     label: "Résolution d impression",
    //     value:
    //       "Jusqu'à 1 200 x 1 200 DPI (noir), Jusqu'à 4 800 x 1 200 DPI (couleur)",
    //   },
    //   { label: "Type de Scanner", value: "Scanner à Plat" },
    //   { label: "Vitesse de numérisation", value: "Jusqu'à 21 secondes" },
    //   { label: "Résolution de Numérisation", value: "Jusqu'à 1200 x 1200 ppp" },
    //   {
    //     label: "Résolution de numérisation optimisée",
    //     value: "Jusqu’à 1200 ppp",
    //   },
    //   { label: "Recto/Verso", value: "Manuel" },
    //   { label: "Connectivite", value: "USB" },
    //   { label: "formats", value: "A4" },
    //   {
    //     label: "Premiére Page Imprimée",
    //     value:
    //       "Noir: (A4, prêt) Vitesse : 14 s - Couleur (A4, prêt) Vitesse : 18 s",
    //   },
    //   {
    //     label: "Alimentation-courant",
    //     value:
    //       "Tension d'entrée : 220 à 240 V CA (+/- 10 %), 50/60 Hz (+/- 3 Hz)",
    //   },
    //   {
    //     label: "Type de Papier pris en charge",
    //     value:
    //       "Papier ordinaire, papiers photo HP, papier mat pour brochure HP ou papier professionnel HP, papier mat pour présentation HP, papier brillant pour brochure HP ou papier professionnel HP, papiers photo jet d'encre, papiers mats jet d'encre, papiers brillant",
    //   },
    //   {
    //     label: "Consommation électrique",
    //     value:
    //       "10 W maximum, 0,07 W (Arrêt), 2,1 W (Veille), 0,88 W (Veille prolongée)",
    //   },
    //   {
    //     label: "Cycle d utilisation Mensuel",
    //     value: "A4: Jusqu'à 1 000 pages - Lettre: Jusqu'à 1 000 pages",
    //   },
    //   {
    //     label: "Alimentation papier standard",
    //     value:
    //       "Bac d'alimentation de 60 feuilles - Bac de sortie de 25 feuilles",
    //   },
    //   { label: "Ecran Tactile", value: "Non" },
    //   { label: "Type ecran", value: "7 segments et icône LCD" },
    //   {
    //     label: "Volume de Pages Mensuel Recommandé",
    //     value: "400 à 800 (Jusqu'à 1000 pages)",
    //   },
    //   { label: "Interfaces standard", value: "1x port USB 2.0 haut débit" },
    //   { label: "Résolution optique", value: "Jusqu'à 1200 x 1200 ppp" },
    //   { label: "Grammage", value: "75 g/m²" },
    //   {
    //     label: "Contenu de L'emballage",
    //     value:
    //       "HP Ink Tank 315 , cartouche d'encre noire HP GT51 (90CC), cartouche d'encre cyan HP GT52 (70CC), cartouche d'encre magenta HP GT52 (70CC), cartouche d'encre jaune HP GT52 (70CC)",
    //   },
    //   { label: "Poids", value: "4,67 kg" },
    //   { label: "Couleur", value: "Noir" },
    //   { label: "Dimensions", value: "525 x 310 x 158 mm" },
    //   { label: "Garantie", value: "1 an" },
    // ],
  },
  {
    _id: "ricoh3",
    img: ricoh3,
    productName: "Fossil Thunder",
    price: "450",
    color: "Blanc",
    badge: true,
    brand: "Fossil",
    des: "Discover the perfect blend of elegance and precision with our exquisite timepieces. Crafted from premium materials and designed for ultimate comfort, each watch ensures reliable performance and versatile style. Embrace sophistication and functionality—experience the art of fine horology.",
    cat: "Garrett Hr Smartwatch",
    // pdf: pdf1,
    // ficheTech: [
    //   { label: "DISPONIBILITÉ", value: "En stock" },
    //   { label: "gtin", value: "Z4B04A" },
    //   { label: "Marque", value: "HP" },
    //   { label: "Destockage", value: "Non" },
    //   { label: "Technologie d impression", value: "Multifonction Jet d'encre" },
    //   { label: "fonctions", value: "Multifonction" },
    //   { label: "Impression", value: "Couleur" },
    //   { label: "Mémoire", value: "Non" },
    //   { label: "FAX", value: "Non" },
    //   { label: "Fonctionnalités", value: "Impression, Copie, Numérisation" },
    //   { label: "Chargement de Documents", value: "Oui" },
    //   { label: "Connecteurs", value: "1 port USB 2.0 haut débit" },
    //   { label: "Vitesse du Processeur", value: "360 MHz" },
    //   {
    //     label: "Impression sans bordure",
    //     value: "Oui, jusqu’à 210 x 297 mm (A4)",
    //   },
    //   { label: "Vitesse d impression Noir", value: "Jusqu'à 19 ppm" },
    //   { label: "Vitesse d impression Couleur", value: "Jusqu'à 15 ppm" },
    //   {
    //     label: "Résolution d'impression Noir",
    //     value: "Jusqu'à 1 200 x 1 200 DPI",
    //   },
    //   {
    //     label: "Résolution d impression Couleur",
    //     value: "Jusqu'à 4 800 x 1 200 DPI (couleur)",
    //   },
    //   {
    //     label: "Résolution d impression",
    //     value:
    //       "Jusqu'à 1 200 x 1 200 DPI (noir), Jusqu'à 4 800 x 1 200 DPI (couleur)",
    //   },
    //   { label: "Type de Scanner", value: "Scanner à Plat" },
    //   { label: "Vitesse de numérisation", value: "Jusqu'à 21 secondes" },
    //   { label: "Résolution de Numérisation", value: "Jusqu'à 1200 x 1200 ppp" },
    //   {
    //     label: "Résolution de numérisation optimisée",
    //     value: "Jusqu’à 1200 ppp",
    //   },
    //   { label: "Recto/Verso", value: "Manuel" },
    //   { label: "Connectivite", value: "USB" },
    //   { label: "formats", value: "A4" },
    //   {
    //     label: "Premiére Page Imprimée",
    //     value:
    //       "Noir: (A4, prêt) Vitesse : 14 s - Couleur (A4, prêt) Vitesse : 18 s",
    //   },
    //   {
    //     label: "Alimentation-courant",
    //     value:
    //       "Tension d'entrée : 220 à 240 V CA (+/- 10 %), 50/60 Hz (+/- 3 Hz)",
    //   },
    //   {
    //     label: "Type de Papier pris en charge",
    //     value:
    //       "Papier ordinaire, papiers photo HP, papier mat pour brochure HP ou papier professionnel HP, papier mat pour présentation HP, papier brillant pour brochure HP ou papier professionnel HP, papiers photo jet d'encre, papiers mats jet d'encre, papiers brillant",
    //   },
    //   {
    //     label: "Consommation électrique",
    //     value:
    //       "10 W maximum, 0,07 W (Arrêt), 2,1 W (Veille), 0,88 W (Veille prolongée)",
    //   },
    //   {
    //     label: "Cycle d utilisation Mensuel",
    //     value: "A4: Jusqu'à 1 000 pages - Lettre: Jusqu'à 1 000 pages",
    //   },
    //   {
    //     label: "Alimentation papier standard",
    //     value:
    //       "Bac d'alimentation de 60 feuilles - Bac de sortie de 25 feuilles",
    //   },
    //   { label: "Ecran Tactile", value: "Non" },
    //   { label: "Type ecran", value: "7 segments et icône LCD" },
    //   {
    //     label: "Volume de Pages Mensuel Recommandé",
    //     value: "400 à 800 (Jusqu'à 1000 pages)",
    //   },
    //   { label: "Interfaces standard", value: "1x port USB 2.0 haut débit" },
    //   { label: "Résolution optique", value: "Jusqu'à 1200 x 1200 ppp" },
    //   { label: "Grammage", value: "75 g/m²" },
    //   {
    //     label: "Contenu de L'emballage",
    //     value:
    //       "HP Ink Tank 315 , cartouche d'encre noire HP GT51 (90CC), cartouche d'encre cyan HP GT52 (70CC), cartouche d'encre magenta HP GT52 (70CC), cartouche d'encre jaune HP GT52 (70CC)",
    //   },
    //   { label: "Poids", value: "4,67 kg" },
    //   { label: "Couleur", value: "Noir" },
    //   { label: "Dimensions", value: "525 x 310 x 158 mm" },
    //   { label: "Garantie", value: "1 an" },
    // ],
  },
  {
    _id: "ricoh4",
    img: ricoh4,
    productName: "Fossil double dial",
    price: "450",
    color: "Blanc",
    badge: true,
    brand: "Fossil",
    des: "Discover the perfect blend of elegance and precision with our exquisite timepieces. Crafted from premium materials and designed for ultimate comfort, each watch ensures reliable performance and versatile style. Embrace sophistication and functionality—experience the art of fine horology.",
    cat: "Garrett Hr Smartwatch",
    // pdf: pdf1,
    // ficheTech: [
    //   { label: "DISPONIBILITÉ", value: "En stock" },
    //   { label: "gtin", value: "Z4B04A" },
    //   { label: "Marque", value: "HP" },
    //   { label: "Destockage", value: "Non" },
    //   { label: "Technologie d impression", value: "Multifonction Jet d'encre" },
    //   { label: "fonctions", value: "Multifonction" },
    //   { label: "Impression", value: "Couleur" },
    //   { label: "Mémoire", value: "Non" },
    //   { label: "FAX", value: "Non" },
    //   { label: "Fonctionnalités", value: "Impression, Copie, Numérisation" },
    //   { label: "Chargement de Documents", value: "Oui" },
    //   { label: "Connecteurs", value: "1 port USB 2.0 haut débit" },
    //   { label: "Vitesse du Processeur", value: "360 MHz" },
    //   {
    //     label: "Impression sans bordure",
    //     value: "Oui, jusqu’à 210 x 297 mm (A4)",
    //   },
    //   { label: "Vitesse d impression Noir", value: "Jusqu'à 19 ppm" },
    //   { label: "Vitesse d impression Couleur", value: "Jusqu'à 15 ppm" },
    //   {
    //     label: "Résolution d'impression Noir",
    //     value: "Jusqu'à 1 200 x 1 200 DPI",
    //   },
    //   {
    //     label: "Résolution d impression Couleur",
    //     value: "Jusqu'à 4 800 x 1 200 DPI (couleur)",
    //   },
    //   {
    //     label: "Résolution d impression",
    //     value:
    //       "Jusqu'à 1 200 x 1 200 DPI (noir), Jusqu'à 4 800 x 1 200 DPI (couleur)",
    //   },
    //   { label: "Type de Scanner", value: "Scanner à Plat" },
    //   { label: "Vitesse de numérisation", value: "Jusqu'à 21 secondes" },
    //   { label: "Résolution de Numérisation", value: "Jusqu'à 1200 x 1200 ppp" },
    //   {
    //     label: "Résolution de numérisation optimisée",
    //     value: "Jusqu’à 1200 ppp",
    //   },
    //   { label: "Recto/Verso", value: "Manuel" },
    //   { label: "Connectivite", value: "USB" },
    //   { label: "formats", value: "A4" },
    //   {
    //     label: "Premiére Page Imprimée",
    //     value:
    //       "Noir: (A4, prêt) Vitesse : 14 s - Couleur (A4, prêt) Vitesse : 18 s",
    //   },
    //   {
    //     label: "Alimentation-courant",
    //     value:
    //       "Tension d'entrée : 220 à 240 V CA (+/- 10 %), 50/60 Hz (+/- 3 Hz)",
    //   },
    //   {
    //     label: "Type de Papier pris en charge",
    //     value:
    //       "Papier ordinaire, papiers photo HP, papier mat pour brochure HP ou papier professionnel HP, papier mat pour présentation HP, papier brillant pour brochure HP ou papier professionnel HP, papiers photo jet d'encre, papiers mats jet d'encre, papiers brillant",
    //   },
    //   {
    //     label: "Consommation électrique",
    //     value:
    //       "10 W maximum, 0,07 W (Arrêt), 2,1 W (Veille), 0,88 W (Veille prolongée)",
    //   },
    //   {
    //     label: "Cycle d utilisation Mensuel",
    //     value: "A4: Jusqu'à 1 000 pages - Lettre: Jusqu'à 1 000 pages",
    //   },
    //   {
    //     label: "Alimentation papier standard",
    //     value:
    //       "Bac d'alimentation de 60 feuilles - Bac de sortie de 25 feuilles",
    //   },
    //   { label: "Ecran Tactile", value: "Non" },
    //   { label: "Type ecran", value: "7 segments et icône LCD" },
    //   {
    //     label: "Volume de Pages Mensuel Recommandé",
    //     value: "400 à 800 (Jusqu'à 1000 pages)",
    //   },
    //   { label: "Interfaces standard", value: "1x port USB 2.0 haut débit" },
    //   { label: "Résolution optique", value: "Jusqu'à 1200 x 1200 ppp" },
    //   { label: "Grammage", value: "75 g/m²" },
    //   {
    //     label: "Contenu de L'emballage",
    //     value:
    //       "HP Ink Tank 315 , cartouche d'encre noire HP GT51 (90CC), cartouche d'encre cyan HP GT52 (70CC), cartouche d'encre magenta HP GT52 (70CC), cartouche d'encre jaune HP GT52 (70CC)",
    //   },
    //   { label: "Poids", value: "4,67 kg" },
    //   { label: "Couleur", value: "Noir" },
    //   { label: "Dimensions", value: "525 x 310 x 158 mm" },
    //   { label: "Garantie", value: "1 an" },
    // ],
  },
  {
    _id: "ricoh5",
    img: ricoh5,
    productName: "Omega Constellation",
    price: "450",
    color: "Blanc",
    badge: true,
    brand: "Omega",
    des: "Discover the perfect blend of elegance and precision with our exquisite timepieces. Crafted from premium materials and designed for ultimate comfort, each watch ensures reliable performance and versatile style. Embrace sophistication and functionality—experience the art of fine horology.",
    cat: "Constellation Co-Axial",
    // pdf: pdf1,
    // ficheTech: [
    //   { label: "DISPONIBILITÉ", value: "En stock" },
    //   { label: "gtin", value: "Z4B04A" },
    //   { label: "Marque", value: "HP" },
    //   { label: "Destockage", value: "Non" },
    //   { label: "Technologie d impression", value: "Multifonction Jet d'encre" },
    //   { label: "fonctions", value: "Multifonction" },
    //   { label: "Impression", value: "Couleur" },
    //   { label: "Mémoire", value: "Non" },
    //   { label: "FAX", value: "Non" },
    //   { label: "Fonctionnalités", value: "Impression, Copie, Numérisation" },
    //   { label: "Chargement de Documents", value: "Oui" },
    //   { label: "Connecteurs", value: "1 port USB 2.0 haut débit" },
    //   { label: "Vitesse du Processeur", value: "360 MHz" },
    //   {
    //     label: "Impression sans bordure",
    //     value: "Oui, jusqu’à 210 x 297 mm (A4)",
    //   },
    //   { label: "Vitesse d impression Noir", value: "Jusqu'à 19 ppm" },
    //   { label: "Vitesse d impression Couleur", value: "Jusqu'à 15 ppm" },
    //   {
    //     label: "Résolution d'impression Noir",
    //     value: "Jusqu'à 1 200 x 1 200 DPI",
    //   },
    //   {
    //     label: "Résolution d impression Couleur",
    //     value: "Jusqu'à 4 800 x 1 200 DPI (couleur)",
    //   },
    //   {
    //     label: "Résolution d impression",
    //     value:
    //       "Jusqu'à 1 200 x 1 200 DPI (noir), Jusqu'à 4 800 x 1 200 DPI (couleur)",
    //   },
    //   { label: "Type de Scanner", value: "Scanner à Plat" },
    //   { label: "Vitesse de numérisation", value: "Jusqu'à 21 secondes" },
    //   { label: "Résolution de Numérisation", value: "Jusqu'à 1200 x 1200 ppp" },
    //   {
    //     label: "Résolution de numérisation optimisée",
    //     value: "Jusqu’à 1200 ppp",
    //   },
    //   { label: "Recto/Verso", value: "Manuel" },
    //   { label: "Connectivite", value: "USB" },
    //   { label: "formats", value: "A4" },
    //   {
    //     label: "Premiére Page Imprimée",
    //     value:
    //       "Noir: (A4, prêt) Vitesse : 14 s - Couleur (A4, prêt) Vitesse : 18 s",
    //   },
    //   {
    //     label: "Alimentation-courant",
    //     value:
    //       "Tension d'entrée : 220 à 240 V CA (+/- 10 %), 50/60 Hz (+/- 3 Hz)",
    //   },
    //   {
    //     label: "Type de Papier pris en charge",
    //     value:
    //       "Papier ordinaire, papiers photo HP, papier mat pour brochure HP ou papier professionnel HP, papier mat pour présentation HP, papier brillant pour brochure HP ou papier professionnel HP, papiers photo jet d'encre, papiers mats jet d'encre, papiers brillant",
    //   },
    //   {
    //     label: "Consommation électrique",
    //     value:
    //       "10 W maximum, 0,07 W (Arrêt), 2,1 W (Veille), 0,88 W (Veille prolongée)",
    //   },
    //   {
    //     label: "Cycle d utilisation Mensuel",
    //     value: "A4: Jusqu'à 1 000 pages - Lettre: Jusqu'à 1 000 pages",
    //   },
    //   {
    //     label: "Alimentation papier standard",
    //     value:
    //       "Bac d'alimentation de 60 feuilles - Bac de sortie de 25 feuilles",
    //   },
    //   { label: "Ecran Tactile", value: "Non" },
    //   { label: "Type ecran", value: "7 segments et icône LCD" },
    //   {
    //     label: "Volume de Pages Mensuel Recommandé",
    //     value: "400 à 800 (Jusqu'à 1000 pages)",
    //   },
    //   { label: "Interfaces standard", value: "1x port USB 2.0 haut débit" },
    //   { label: "Résolution optique", value: "Jusqu'à 1200 x 1200 ppp" },
    //   { label: "Grammage", value: "75 g/m²" },
    //   {
    //     label: "Contenu de L'emballage",
    //     value:
    //       "HP Ink Tank 315 , cartouche d'encre noire HP GT51 (90CC), cartouche d'encre cyan HP GT52 (70CC), cartouche d'encre magenta HP GT52 (70CC), cartouche d'encre jaune HP GT52 (70CC)",
    //   },
    //   { label: "Poids", value: "4,67 kg" },
    //   { label: "Couleur", value: "Noir" },
    //   { label: "Dimensions", value: "525 x 310 x 158 mm" },
    //   { label: "Garantie", value: "1 an" },
    // ],
  },

  // =================== imprimante ricoh =================

  {
    _id: "espson1",
    img: espson1,
    productName: "Co-Axial Radial Omega",
    price: "450",
    color: "Blanc",
    badge: true,
    brand: "Omega",
    des: "Discover the perfect blend of elegance and precision with our exquisite timepieces. Crafted from premium materials and designed for ultimate comfort, each watch ensures reliable performance and versatile style. Embrace sophistication and functionality—experience the art of fine horology.",
    cat: "Constellation Co-Axial",
    // pdf: pdf1,
    // ficheTech: [
    //   { label: "DISPONIBILITÉ", value: "En stock" },
    //   { label: "gtin", value: "Z4B04A" },
    //   { label: "Marque", value: "HP" },
    //   { label: "Destockage", value: "Non" },
    //   { label: "Technologie d impression", value: "Multifonction Jet d'encre" },
    //   { label: "fonctions", value: "Multifonction" },
    //   { label: "Impression", value: "Couleur" },
    //   { label: "Mémoire", value: "Non" },
    //   { label: "FAX", value: "Non" },
    //   { label: "Fonctionnalités", value: "Impression, Copie, Numérisation" },
    //   { label: "Chargement de Documents", value: "Oui" },
    //   { label: "Connecteurs", value: "1 port USB 2.0 haut débit" },
    //   { label: "Vitesse du Processeur", value: "360 MHz" },
    //   {
    //     label: "Impression sans bordure",
    //     value: "Oui, jusqu’à 210 x 297 mm (A4)",
    //   },
    //   { label: "Vitesse d impression Noir", value: "Jusqu'à 19 ppm" },
    //   { label: "Vitesse d impression Couleur", value: "Jusqu'à 15 ppm" },
    //   {
    //     label: "Résolution d'impression Noir",
    //     value: "Jusqu'à 1 200 x 1 200 DPI",
    //   },
    //   {
    //     label: "Résolution d impression Couleur",
    //     value: "Jusqu'à 4 800 x 1 200 DPI (couleur)",
    //   },
    //   {
    //     label: "Résolution d impression",
    //     value:
    //       "Jusqu'à 1 200 x 1 200 DPI (noir), Jusqu'à 4 800 x 1 200 DPI (couleur)",
    //   },
    //   { label: "Type de Scanner", value: "Scanner à Plat" },
    //   { label: "Vitesse de numérisation", value: "Jusqu'à 21 secondes" },
    //   { label: "Résolution de Numérisation", value: "Jusqu'à 1200 x 1200 ppp" },
    //   {
    //     label: "Résolution de numérisation optimisée",
    //     value: "Jusqu’à 1200 ppp",
    //   },
    //   { label: "Recto/Verso", value: "Manuel" },
    //   { label: "Connectivite", value: "USB" },
    //   { label: "formats", value: "A4" },
    //   {
    //     label: "Premiére Page Imprimée",
    //     value:
    //       "Noir: (A4, prêt) Vitesse : 14 s - Couleur (A4, prêt) Vitesse : 18 s",
    //   },
    //   {
    //     label: "Alimentation-courant",
    //     value:
    //       "Tension d'entrée : 220 à 240 V CA (+/- 10 %), 50/60 Hz (+/- 3 Hz)",
    //   },
    //   {
    //     label: "Type de Papier pris en charge",
    //     value:
    //       "Papier ordinaire, papiers photo HP, papier mat pour brochure HP ou papier professionnel HP, papier mat pour présentation HP, papier brillant pour brochure HP ou papier professionnel HP, papiers photo jet d'encre, papiers mats jet d'encre, papiers brillant",
    //   },
    //   {
    //     label: "Consommation électrique",
    //     value:
    //       "10 W maximum, 0,07 W (Arrêt), 2,1 W (Veille), 0,88 W (Veille prolongée)",
    //   },
    //   {
    //     label: "Cycle d utilisation Mensuel",
    //     value: "A4: Jusqu'à 1 000 pages - Lettre: Jusqu'à 1 000 pages",
    //   },
    //   {
    //     label: "Alimentation papier standard",
    //     value:
    //       "Bac d'alimentation de 60 feuilles - Bac de sortie de 25 feuilles",
    //   },
    //   { label: "Ecran Tactile", value: "Non" },
    //   { label: "Type ecran", value: "7 segments et icône LCD" },
    //   {
    //     label: "Volume de Pages Mensuel Recommandé",
    //     value: "400 à 800 (Jusqu'à 1000 pages)",
    //   },
    //   { label: "Interfaces standard", value: "1x port USB 2.0 haut débit" },
    //   { label: "Résolution optique", value: "Jusqu'à 1200 x 1200 ppp" },
    //   { label: "Grammage", value: "75 g/m²" },
    //   {
    //     label: "Contenu de L'emballage",
    //     value:
    //       "HP Ink Tank 315 , cartouche d'encre noire HP GT51 (90CC), cartouche d'encre cyan HP GT52 (70CC), cartouche d'encre magenta HP GT52 (70CC), cartouche d'encre jaune HP GT52 (70CC)",
    //   },
    //   { label: "Poids", value: "4,67 kg" },
    //   { label: "Couleur", value: "Noir" },
    //   { label: "Dimensions", value: "525 x 310 x 158 mm" },
    //   { label: "Garantie", value: "1 an" },
    // ],
  },

  {
    _id: "espson2",
    img: espson2,
    productName: "Omega Supremo",
    price: "450",
    color: "Blanc",
    badge: true,
    brand: "Omega",
    des: "Discover the perfect blend of elegance and precision with our exquisite timepieces. Crafted from premium materials and designed for ultimate comfort, each watch ensures reliable performance and versatile style. Embrace sophistication and functionality—experience the art of fine horology.",
    cat: "Constellation Co-Axial",
    // pdf: pdf1,
    // ficheTech: [
    //   { label: "DISPONIBILITÉ", value: "En stock" },
    //   { label: "gtin", value: "Z4B04A" },
    //   { label: "Marque", value: "HP" },
    //   { label: "Destockage", value: "Non" },
    //   { label: "Technologie d impression", value: "Multifonction Jet d'encre" },
    //   { label: "fonctions", value: "Multifonction" },
    //   { label: "Impression", value: "Couleur" },
    //   { label: "Mémoire", value: "Non" },
    //   { label: "FAX", value: "Non" },
    //   { label: "Fonctionnalités", value: "Impression, Copie, Numérisation" },
    //   { label: "Chargement de Documents", value: "Oui" },
    //   { label: "Connecteurs", value: "1 port USB 2.0 haut débit" },
    //   { label: "Vitesse du Processeur", value: "360 MHz" },
    //   {
    //     label: "Impression sans bordure",
    //     value: "Oui, jusqu’à 210 x 297 mm (A4)",
    //   },
    //   { label: "Vitesse d impression Noir", value: "Jusqu'à 19 ppm" },
    //   { label: "Vitesse d impression Couleur", value: "Jusqu'à 15 ppm" },
    //   {
    //     label: "Résolution d'impression Noir",
    //     value: "Jusqu'à 1 200 x 1 200 DPI",
    //   },
    //   {
    //     label: "Résolution d impression Couleur",
    //     value: "Jusqu'à 4 800 x 1 200 DPI (couleur)",
    //   },
    //   {
    //     label: "Résolution d impression",
    //     value:
    //       "Jusqu'à 1 200 x 1 200 DPI (noir), Jusqu'à 4 800 x 1 200 DPI (couleur)",
    //   },
    //   { label: "Type de Scanner", value: "Scanner à Plat" },
    //   { label: "Vitesse de numérisation", value: "Jusqu'à 21 secondes" },
    //   { label: "Résolution de Numérisation", value: "Jusqu'à 1200 x 1200 ppp" },
    //   {
    //     label: "Résolution de numérisation optimisée",
    //     value: "Jusqu’à 1200 ppp",
    //   },
    //   { label: "Recto/Verso", value: "Manuel" },
    //   { label: "Connectivite", value: "USB" },
    //   { label: "formats", value: "A4" },
    //   {
    //     label: "Premiére Page Imprimée",
    //     value:
    //       "Noir: (A4, prêt) Vitesse : 14 s - Couleur (A4, prêt) Vitesse : 18 s",
    //   },
    //   {
    //     label: "Alimentation-courant",
    //     value:
    //       "Tension d'entrée : 220 à 240 V CA (+/- 10 %), 50/60 Hz (+/- 3 Hz)",
    //   },
    //   {
    //     label: "Type de Papier pris en charge",
    //     value:
    //       "Papier ordinaire, papiers photo HP, papier mat pour brochure HP ou papier professionnel HP, papier mat pour présentation HP, papier brillant pour brochure HP ou papier professionnel HP, papiers photo jet d'encre, papiers mats jet d'encre, papiers brillant",
    //   },
    //   {
    //     label: "Consommation électrique",
    //     value:
    //       "10 W maximum, 0,07 W (Arrêt), 2,1 W (Veille), 0,88 W (Veille prolongée)",
    //   },
    //   {
    //     label: "Cycle d utilisation Mensuel",
    //     value: "A4: Jusqu'à 1 000 pages - Lettre: Jusqu'à 1 000 pages",
    //   },
    //   {
    //     label: "Alimentation papier standard",
    //     value:
    //       "Bac d'alimentation de 60 feuilles - Bac de sortie de 25 feuilles",
    //   },
    //   { label: "Ecran Tactile", value: "Non" },
    //   { label: "Type ecran", value: "7 segments et icône LCD" },
    //   {
    //     label: "Volume de Pages Mensuel Recommandé",
    //     value: "400 à 800 (Jusqu'à 1000 pages)",
    //   },
    //   { label: "Interfaces standard", value: "1x port USB 2.0 haut débit" },
    //   { label: "Résolution optique", value: "Jusqu'à 1200 x 1200 ppp" },
    //   { label: "Grammage", value: "75 g/m²" },
    //   {
    //     label: "Contenu de L'emballage",
    //     value:
    //       "HP Ink Tank 315 , cartouche d'encre noire HP GT51 (90CC), cartouche d'encre cyan HP GT52 (70CC), cartouche d'encre magenta HP GT52 (70CC), cartouche d'encre jaune HP GT52 (70CC)",
    //   },
    //   { label: "Poids", value: "4,67 kg" },
    //   { label: "Couleur", value: "Noir" },
    //   { label: "Dimensions", value: "525 x 310 x 158 mm" },
    //   { label: "Garantie", value: "1 an" },
    // ],
  },
];
